### ISSUE TITLE
did you solve this?

### ISSUE THREAD

**Issue by sidalihallak** [rreusser/react-native-android-intent-issue#1]

**Comment by rreusser** [comment]
Yes, see the solution listed on the related issue: https://github.com/facebook/react-native/issues/7079

> Adding android:launchMode="singleTask" to the MainActivity definition prevents multiple instances by routing the intent to the existing activity, but then getInitialURL is not adequate to handle deep links since it's no longer an initial URL. The solution in turn is for onNewIntent of MainActivity to send an 'openURL' event through RCTDeviceEventEmitter, which can be received by a (trivially) completed version of Linking.addEventListener for Android—which unless I'm mistaken is just a copy/paste job once the device event emitter is hooked up to onNewIntent.

I think the takeaway was that it was going too far to make that choice for *everyone*, and that it's a configuration issue beyond that. There are also a couple android-specific notes here:

See also: https://facebook.github.io/react-native/docs/linking.html

**Comment by rreusser** [comment]
(Also, I think the onNewIntent part may have made it into a PR and into the linking library for getIntialURL, but it's been a couple years so I'm not 100% certain)

**Comment by sidalihallak** [comment]
Thanks I already solved it , I used onNewIntent to fire events , thanks
